[package]
name = "rust-async-lock-restore-test"
version = "0.1.100"
edition = "2021"

# 19.3.2023 12:38
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.1"
